[2025-04-12T18:19:02.712+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T18:19:02.758+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T18:19:01.385654+00:00 [queued]>
[2025-04-12T18:19:02.772+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T18:19:01.385654+00:00 [queued]>
[2025-04-12T18:19:02.773+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-12T18:19:02.793+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_spark_submit> on 2025-04-12 18:19:01.385654+00:00
[2025-04-12T18:19:02.806+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T18:19:02.810+0000] {standard_task_runner.py:72} INFO - Started process 247 to run task
[2025-04-12T18:19:02.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_client_csv_to_delta', 'run_spark_submit', 'manual__2025-04-12T18:19:01.385654+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/load_client_dags.py', '--cfg-path', '/tmp/tmpevh1x6cg']
[2025-04-12T18:19:02.813+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_spark_submit
[2025-04-12T18:19:02.912+0000] {task_command.py:467} INFO - Running <TaskInstance: load_client_csv_to_delta.run_spark_submit manual__2025-04-12T18:19:01.385654+00:00 [running]> on host e7fcf395747c
[2025-04-12T18:19:03.108+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_client_csv_to_delta' AIRFLOW_CTX_TASK_ID='run_spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T18:19:01.385654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T18:19:01.385654+00:00'
[2025-04-12T18:19:03.110+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T18:19:03.137+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-12T18:19:03.138+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n /opt/spark/bin/spark-submit   --master local[*]   --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension   --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog   --conf spark.jars=/opt/spark/jar/delta-spark_2.13-3.3.0.jar   --py-files /home/djuybu/Desktop/BigData_BigProject/src/data_loaders/transactions/csv/load_client_csv.py']
[2025-04-12T18:19:03.155+0000] {subprocess.py:99} INFO - Output:
[2025-04-12T18:19:03.188+0000] {subprocess.py:106} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-12T18:19:03.190+0000] {subprocess.py:106} INFO - JAVA_HOME is not set
[2025-04-12T18:19:03.191+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-12T18:19:03.217+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T18:19:03.224+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_client_csv_to_delta, task_id=run_spark_submit, run_id=manual__2025-04-12T18:19:01.385654+00:00, execution_date=20250412T181901, start_date=20250412T181902, end_date=20250412T181903
[2025-04-12T18:19:03.251+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T18:19:03.254+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_spark_submit (Bash command failed. The command returned a non-zero exit code 1.; 247)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-12T18:19:03.320+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-12T18:19:03.356+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T18:19:03.358+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
